title = "ElseyWorld"
languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[params.author]
  name = "Nick Elsey"
  image = "img/nick_author.jpg"
  headline = "Writing on travel, food and technology"
  bio = "30 years in technology, now focusing on health, happiness, family and travel."
  links = [
    { linkedin = "https://www.linkedin.com/in/nickelsey/" }
  ]