backend:
  name: github
  repo: NickElseySpelloC/ElseyWorld
  branch: main
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "blog"
    label: "Travel Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Nick Elsey" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Categories", name: "categories", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "articles"
    label: "Lynn's Articles"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Lynn Elsey" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Categories", name: "categories", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }