backend:
  name: github
  repo: NickElseySpelloC/ElseyWorld
  branch: main
  base_url: https://elseyworks.com
  auth_endpoint: /oauth
media_folder: "static/img/uploads"
public_folder: "/img/uploads"
collections:
  - name: "blog"
    label: "Nick's Travel Blog"
    folder: "content/blog"
    create: true
    media_folder: "static/img/blog"
    public_folder: "/img/blog"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Nick Elsey" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Cover Image", name: "cover", widget: "image", required: false }
      - { label: "Categories", name: "categories", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "articles"
    label: "Lynn's Articles"
    folder: "content/articles"
    create: true
    media_folder: "static/img/articles"
    public_folder: "/img/articles"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Lynn Elsey" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Cover Image", name: "cover", widget: "image", required: false }
      - { label: "Categories", name: "categories", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }