backend:
  name: github
  repo: NickElseySpelloC/ElseyWorld
  branch: main
  base_url: https://elseyworld.com
  auth_endpoint: /oauth
media_folder: "static/img/uploads"
public_folder: "/img/uploads"
collections:
  - name: "blog_asia_2009"
    label: "Travel Blog: Asia 2009"
    folder: "content/blog/asia-2009"
    create: true
    media_folder: ""
    public_folder: ""
    slug: "{{slug}}"
    path: "{{slug}}/index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}" }
      - { name: "author", widget: "hidden", default: "Nick Elsey" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Thumbnail Image", name: "thumbnail", widget: "image", required: false }
      - { name: "categories", widget: "hidden", default: ["Nick", "Asia 2009"] }
      - { label: "Aliases", name: "aliases", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "blog_australia_2002_trip_1"
    label: "Travel Blog: Australia 2002 Trip 1"
    folder: "content/blog/australia-2002-trip-1"
    create: true
    media_folder: ""
    public_folder: ""
    slug: "{{slug}}"
    path: "{{slug}}/index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}" }
      - { name: "author", widget: "hidden", default: "Nick Elsey" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Thumbnail Image", name: "thumbnail", widget: "image", required: false }
      - { name: "categories", widget: "hidden", default: ["Nick", "Australia 2002 Trip 1"] }
      - { label: "Aliases", name: "aliases", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "blog_australia_2002_trip_2"
    label: "Travel Blog: Australia 2002 Trip 2"
    folder: "content/blog/australia-2002-trip-2"
    create: true
    media_folder: ""
    public_folder: ""
    slug: "{{slug}}"
    path: "{{slug}}/index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}" }
      - { name: "author", widget: "hidden", default: "Nick Elsey" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Thumbnail Image", name: "thumbnail", widget: "image", required: false }
      - { name: "categories", widget: "hidden", default: ["Nick", "Australia 2002 Trip 2"] }
      - { label: "Aliases", name: "aliases", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "blog_australia_2009"
    label: "Travel Blog: Australia 2009"
    folder: "content/blog/australia-2009"
    create: true
    media_folder: ""
    public_folder: ""
    slug: "{{slug}}"
    path: "{{slug}}/index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}" }
      - { name: "author", widget: "hidden", default: "Nick Elsey" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Thumbnail Image", name: "thumbnail", widget: "image", required: false }
      - { name: "categories", widget: "hidden", default: ["Nick", "Australia 2009"] }
      - { label: "Aliases", name: "aliases", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "blog_moving_to_dc"
    label: "Travel Blog: Moving to DC"
    folder: "content/blog/moving-to-dc"
    create: true
    media_folder: ""
    public_folder: ""
    slug: "{{slug}}"
    path: "{{slug}}/index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}" }
      - { name: "author", widget: "hidden", default: "Nick Elsey" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Thumbnail Image", name: "thumbnail", widget: "image", required: false }
      - { name: "categories", widget: "hidden", default: ["Nick", "Moving to DC"] }
      - { label: "Aliases", name: "aliases", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "blog_south_pacific_1997"
    label: "Travel Blog: South Pacific 1997"
    folder: "content/blog/south-pacific-1997"
    create: true
    media_folder: ""
    public_folder: ""
    slug: "{{slug}}"
    path: "{{slug}}/index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}" }
      - { name: "author", widget: "hidden", default: "Nick Elsey" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Thumbnail Image", name: "thumbnail", widget: "image", required: false }
      - { name: "categories", widget: "hidden", default: ["Nick", "South Pacific 1997"] }
      - { label: "Aliases", name: "aliases", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "articles_business"
    label: "Articles: Business"
    folder: "content/articles/business"
    create: true
    media_folder: ""
    public_folder: ""
    slug: "{{slug}}"
    path: "{{slug}}/index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}" }
      - { name: "author", widget: "hidden", default: "Lynn Elsey" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Thumbnail Image", name: "thumbnail", widget: "image", required: false }
      - { name: "categories", widget: "hidden", default: ["Lynn", "Business"] }
      - { label: "Aliases", name: "aliases", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "articles_careers"
    label: "Articles: Careers"
    folder: "content/articles/careers"
    create: true
    media_folder: ""
    public_folder: ""
    slug: "{{slug}}"
    path: "{{slug}}/index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}" }
      - { name: "author", widget: "hidden", default: "Lynn Elsey" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Thumbnail Image", name: "thumbnail", widget: "image", required: false }
      - { name: "categories", widget: "hidden", default: ["Lynn", "Careers"] }
      - { label: "Aliases", name: "aliases", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "articles_food_travel"
    label: "Articles: Food & Travel"
    folder: "content/articles/food-travel"
    create: true
    media_folder: ""
    public_folder: ""
    slug: "{{slug}}"
    path: "{{slug}}/index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}" }
      - { name: "author", widget: "hidden", default: "Lynn Elsey" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Thumbnail Image", name: "thumbnail", widget: "image", required: false }
      - { name: "categories", widget: "hidden", default: ["Lynn", "Food Travel"] }
      - { label: "Aliases", name: "aliases", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "articles_health"
    label: "Articles: Health"
    folder: "content/articles/health"
    create: true
    media_folder: ""
    public_folder: ""
    slug: "{{slug}}"
    path: "{{slug}}/index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}" }
      - { name: "author", widget: "hidden", default: "Lynn Elsey" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Thumbnail Image", name: "thumbnail", widget: "image", required: false }
      - { name: "categories", widget: "hidden", default: ["Lynn", "Health"] }
      - { label: "Aliases", name: "aliases", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "articles_magazines"
    label: "Articles: Magazines"
    folder: "content/articles/magazines"
    create: true
    media_folder: ""
    public_folder: ""
    slug: "{{slug}}"
    path: "{{slug}}/index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}" }
      - { name: "author", widget: "hidden", default: "Lynn Elsey" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Thumbnail Image", name: "thumbnail", widget: "image", required: false }
      - { name: "categories", widget: "hidden", default: ["Lynn", "Magazines"] }
      - { label: "Aliases", name: "aliases", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }